<?php

namespace App\Command;

use App\Docker\NavidromeContainerConfig;
use App\Repository\PlaylistDefinitionRepository;
use Cron\CronExpression;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'app:cron:dump',
    description: 'Print a supercronic-compatible crontab from enabled playlist definitions.',
)]
class DumpCronCommand extends Command
{
    public function __construct(
        private readonly PlaylistDefinitionRepository $repository,
        private readonly NavidromeContainerConfig $containerConfig,
        private readonly string $projectDir,
        private readonly string $statsRefreshSchedule,
        private readonly string $loveSyncSchedule = '',
        private readonly string $rematchSchedule = '',
        private readonly string $dbBackupSchedule = '',
        private readonly string $navidromeBackupSchedule = '',
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $output->writeln('# Generated by app:cron:dump on ' . (new \DateTimeImmutable())->format(DATE_ATOM));
        $output->writeln('# Re-run this command after editing playlist definitions.');
        $output->writeln('');

        $bin = $this->projectDir . '/bin/console';

        foreach ($this->repository->findScheduledEnabled() as $def) {
            $schedule = $def->getSchedule();
            if (!$schedule) {
                continue;
            }
            try {
                new CronExpression($schedule);
            } catch (\Throwable $e) {
                $output->writeln('# SKIP "' . $def->getName() . '": invalid schedule (' . $e->getMessage() . ')');
                continue;
            }

            $output->writeln(sprintf(
                '%s php %s app:playlist:run %d',
                $schedule,
                $bin,
                (int) $def->getId(),
            ));
        }

        if ($this->statsRefreshSchedule !== '') {
            try {
                new CronExpression($this->statsRefreshSchedule);
                $output->writeln('');
                $output->writeln('# Stats snapshots refresh (STATS_REFRESH_SCHEDULE)');
                $output->writeln(sprintf(
                    '%s php %s app:stats:compute',
                    $this->statsRefreshSchedule,
                    $bin,
                ));
            } catch (\Throwable $e) {
                $output->writeln('# SKIP stats refresh: invalid STATS_REFRESH_SCHEDULE (' . $e->getMessage() . ')');
            }
        }

        if ($this->loveSyncSchedule !== '') {
            try {
                new CronExpression($this->loveSyncSchedule);
                $output->writeln('');
                $output->writeln('# Sync Last.fm loved ↔ Navidrome starred (LASTFM_LOVE_SYNC_SCHEDULE)');
                $output->writeln(sprintf(
                    '%s php %s app:lastfm:sync-loved',
                    $this->loveSyncSchedule,
                    $bin,
                ));
            } catch (\Throwable $e) {
                $output->writeln('# SKIP love-sync: invalid LASTFM_LOVE_SYNC_SCHEDULE (' . $e->getMessage() . ')');
            }
        }

        if ($this->rematchSchedule !== '') {
            try {
                new CronExpression($this->rematchSchedule);
                $output->writeln('');
                $output->writeln('# Re-match Last.fm unmatched scrobbles (LASTFM_REMATCH_SCHEDULE)');
                $autoStopFlag = $this->containerConfig->isConfigured() ? ' --auto-stop' : '';
                $output->writeln(sprintf(
                    '%s php %s app:lastfm:rematch%s',
                    $this->rematchSchedule,
                    $bin,
                    $autoStopFlag,
                ));
            } catch (\Throwable $e) {
                $output->writeln('# SKIP rematch: invalid LASTFM_REMATCH_SCHEDULE (' . $e->getMessage() . ')');
            }
        }

        if ($this->dbBackupSchedule !== '') {
            try {
                new CronExpression($this->dbBackupSchedule);
                $output->writeln('');
                $output->writeln('# Backup of the tool\'s local DB (DB_BACKUP_SCHEDULE)');
                $output->writeln(sprintf(
                    '%s php %s app:db:backup',
                    $this->dbBackupSchedule,
                    $bin,
                ));
            } catch (\Throwable $e) {
                $output->writeln('# SKIP db backup: invalid DB_BACKUP_SCHEDULE (' . $e->getMessage() . ')');
            }
        }

        if ($this->navidromeBackupSchedule !== '') {
            try {
                new CronExpression($this->navidromeBackupSchedule);
                $output->writeln('');
                $output->writeln('# Backup of the Navidrome library DB (NAVIDROME_BACKUP_SCHEDULE)');
                // Auto-stop only when the container management is wired —
                // otherwise --auto-stop fails immediately with « not configured ».
                // Without --auto-stop the pre-flight blocks the run if Navidrome
                // is up, so the user has to either configure NAVIDROME_CONTAINER_NAME
                // or stop Navidrome out-of-band.
                $autoStopFlag = $this->containerConfig->isConfigured() ? ' --auto-stop' : '';
                $output->writeln(sprintf(
                    '%s php %s app:navidrome:backup%s',
                    $this->navidromeBackupSchedule,
                    $bin,
                    $autoStopFlag,
                ));
            } catch (\Throwable $e) {
                $output->writeln('# SKIP navidrome backup: invalid NAVIDROME_BACKUP_SCHEDULE (' . $e->getMessage() . ')');
            }
        }

        $output->writeln('');
        $output->writeln('# Daily purge of run_history older than RUN_HISTORY_RETENTION_DAYS');
        $output->writeln(sprintf('30 4 * * * php %s app:history:purge', $bin));

        return Command::SUCCESS;
    }
}
