framework:
    messenger:
        transports:
            async:
                dsn: 'doctrine://default?queue_name=async'
                options:
                    auto_setup: true
                retry_strategy:
                    max_retries: 0

        routing:
            App\Message\RunLastFmFetchMessage: async
            App\Message\RunLastFmProcessMessage: async
            App\Message\RunLastFmRematchMessage: async
            App\Message\RunLastFmSyncLovedMessage: async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
