framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 1000
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2

        routing:
            'App\Message\FetchLastFmMessage': async
            'App\Message\SyncNavidromeMessage': async
            'App\Message\SyncStrawberryMessage': async
            'App\Message\RematchMessage': async
            'App\Message\SuggestAliasesMusicBrainzMessage': async
            'App\Message\GeneratePlaylistsMessage': async
            'App\Message\ComputeRecommendationsMessage': async
